# Generated by Django 5.1.4 on 2025-01-14 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0004_faq_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='preferences',
            new_name='bio',
        ),
    ]
